# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abrege
  namespace: abrege
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: abrege
  strategy:
    rollingUpdate:
      maxSurge: "25%"
      maxUnavailable: "25%"
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: abrege
    spec:
      containers:
      - name: abrege
        image: ghcr.io/ia-generative/abrege-abrege:latest
#        command: ["npm", "run"]
#        args: ["$(NODE_ENV)"]
        env:
#        - name: FRONT_PORT
#          value: "3000"
#        - name: NODE_ENV
#          value: development
        - name: VITE_RECHERCHE_PLUS_URL
          value: https://demo1.numerique-interieur.com
        - name: VITE_PDF_URL
          value: https://demo7.numerique-interieur.com
        - name: VITE_RESUME_URL
          value: https://demo4.numerique-interieur.com
        - name: VITE_CHAT_URL
          value: https://chatbot.numerique-interieur.com
        - name: VITE_PDF_PLUS_URL
          value: https://demo2.numerique-interieur.com
        - name: VITE_SQL_URL
          value: https://demo14.numerique-interieur.com
        - name: ENVIRONMENT
          value: development
        - name: VITE_RECHERCHE_INTERNET_URL
          value: https://demo5.numerique-interieur.com
        ports:
        - containerPort: 8080
          protocol: TCP
#        volumeMounts:
#        - name: abrege-code
#          mountPath: /usr/src/app
#        - name: abrege-node-modules
#          mountPath: /usr/src/app/node_modules

      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: github-regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

#      volumes:
#      - name: abrege-code
#        persistentVolumeClaim:
#          claimName: abrege-code-pvc
#      - name: abrege-node-modules
#        persistentVolumeClaim:
#          claimName: abrege-node-modules-pvc

---
# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: abrege-code-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: abrege-node-modules-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: abrege-service
spec:
  type: ClusterIP
  selector:
    app: abrege
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/session-cookie-name: route
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required - demo
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
  name: chatpi.numerique-interieur.com
spec:
  ingressClassName: public
  rules:
  - host: chatpi.numerique-interieur.com
    http:
      paths:
      - backend:
          service:
            name: abrege-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - chatpi.numerique-interieur.com
    secretName: chatpi.numerique-interieur.com-tls