# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abrege
  namespace: abrege
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: abrege
  strategy:
    rollingUpdate:
      maxSurge: "25%"
      maxUnavailable: "25%"
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: abrege
    spec:
      containers:
      - name: abrege
        image: ghcr.io/ia-generative/abrege-abrege:latest
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: secret-abrege
              key: OPENAI_API_KEY
        - name: OPENAI_API_BASE
          valueFrom:
            secretKeyRef:
              name: secret-abrege
              key: OPENAI_API_BASE
        - name: EMBEDDING_MODEL_PATH
          valueFrom:
            secretKeyRef:
              name: secret-abrege
              key: EMBEDDING_MODEL_PATH
        - name: OPENAI_EMBEDDING_API_KEY
          valueFrom:
            secretKeyRef:
              name: secret-abrege
              key: OPENAI_EMBEDDING_API_KEY
        - name: OPENAI_EMBEDDING_API_BASE
          valueFrom:
            secretKeyRef:
              name: secret-abrege
              key: OPENAI_EMBEDDING_API_BASE
        ports:
        - containerPort: 8000
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: github-regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: abrege-service
spec:
  type: ClusterIP
  selector:
    app: abrege
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: abrege-streamlit-service
spec:
  type: ClusterIP
  selector:
    app: abrege
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/session-cookie-name: route
  name: abrege.c0.cloud-pi-native.com
spec:
  ingressClassName: public
  rules:
  - host: abrege.c0.cloud-pi-native.com
    http:
      paths:
      - backend:
          service:
            name: abrege-streamlit-service
            port:
              number: 80
        path: /streamlit
        pathType: Prefix
      - backend:
          service:
            name: abrege-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - abrege.c0.cloud-pi-native.com
    secretName: abrege.c0.cloud-pi-native.com-tls