# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: PLACEHOLDER_FOR_NAME
  namespace: abrege
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: PLACEHOLDER_FOR_NAME
  strategy:
    rollingUpdate:
      maxSurge: "25%"
      maxUnavailable: "25%"
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: PLACEHOLDER_FOR_NAME
      annotations:
        redeploy-hash: "PLACEHOLDER_FOR_IMAGE_HASH"

    spec:
      containers:
      - name: PLACEHOLDER_FOR_NAME-api
        image: ghcr.io/ia-generative/abrege-api:latest
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: secret-abrege
              key: OPENAI_API_KEY
        - name: OPENAI_API_BASE
          valueFrom:
            secretKeyRef:
              name: secret-abrege
              key: OPENAI_API_BASE
        - name: EMBEDDING_MODEL_PATH
          valueFrom:
            secretKeyRef:
              name: secret-abrege
              key: EMBEDDING_MODEL_PATH
        - name: OPENAI_EMBEDDING_API_KEY
          valueFrom:
            secretKeyRef:
              name: secret-abrege
              key: OPENAI_EMBEDDING_API_KEY
        - name: OPENAI_EMBEDDING_API_BASE
          valueFrom:
            secretKeyRef:
              name: secret-abrege
              key: OPENAI_EMBEDDING_API_BASE
        - name: PADDLE_OCR_URL
          valueFrom:
            secretKeyRef:
              name: secret-abrege
              key: PADDLE_OCR_URL
        - name: PADDLE_OCR_TOKEN
          valueFrom:
            secretKeyRef:
              name: secret-abrege
              key: PADDLE_OCR_TOKEN
        - name: CORS_REGEXP
          valueFrom:
            secretKeyRef:
              name: secret-abrege
              key: CORS_REGEXP
        ports:
        - containerPort: 8000
          protocol: TCP

      - name: PLACEHOLDER_FOR_NAME-front
        image: ghcr.io/ia-generative/abrege-front:latest
        env:
          - name: API_BASE
            value: 0.0.0.0
        ports:
        - containerPort: 8080
          protocol: TCP

      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: github-regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: PLACEHOLDER_FOR_NAME-service
spec:
  type: ClusterIP
  selector:
    app: PLACEHOLDER_FOR_NAME
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: PLACEHOLDER_FOR_NAME-streamlit-service
spec:
  type: ClusterIP
  selector:
    app: PLACEHOLDER_FOR_NAME
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/session-cookie-name: route
    #nginx.ingress.kubernetes.io/whitelist-source-range: 127.0.0.0/16,192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,51.159.0.0/16,163.172.0.0/16,91.121.239.0/28,77.158.219.0/24,92.103.164.0/24,185.24.186.0/24,82.64.241.24/32,37.67.157.185/32

  name: PLACEHOLDER_FOR_NAME.c0.cloud-pi-native.com
spec:
  ingressClassName: public
  rules:
  - host: PLACEHOLDER_FOR_NAME.c0.cloud-pi-native.com
    http:
      paths:
      - backend:
          service:
            name: PLACEHOLDER_FOR_NAME-service
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: PLACEHOLDER_FOR_NAME-streamlit.c0.cloud-pi-native.com
    http:
      paths:
      - backend:
          service:
            name: PLACEHOLDER_FOR_NAME-streamlit-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - PLACEHOLDER_FOR_NAME.c0.cloud-pi-native.com
    secretName: PLACEHOLDER_FOR_NAME.c0.cloud-pi-native.com-tls
  - hosts:
    - PLACEHOLDER_FOR_NAME-streamlit.c0.cloud-pi-native.com
    secretName: PLACEHOLDER_FOR_NAME-streamlit.c0.cloud-pi-native.com-tls
