[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "abrege"
version = "0.0.1"
authors = []
description = "A small langchain summary builder with extractive summary method to speed up summary process"
requires-python = "==3.11.9"
classifiers = [
    "Programming Language :: Python :: 3"
]
dynamic = ["dependencies", "readme"]

[tool.setuptools]
py-modules = ["abrege"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
readme = {file = ["README.md"]}


[tool.poetry]
name = "abrege"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "=3.11.9"
langchain = "^0.1.16"
pytest = "^8.2.0"
langchain-openai = "^0.1.6"
networkx = {extras = ["default"], version = "^3.3"}
nltk = "^3.8.1"
scikit-learn = "^1.4.2"
fastapi = "^0.111.0"
pypdf = "^4.2.0"
chromadb = "^0.5.0"
docx2txt = "^0.8"
pypandoc-binary = "^1.13"
unstructured = "^0.13.6"
python-docx = "^1.1.2"
numpy = "^1.26.4"
transformers = "^4.40.2"
streamlit = "^1.34.0"
streamlit-dsfr = "^0.0.14"
validators = "^0.28.1"
pymupdf = "^1.24.5"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"

[tool.pytest.ini_options]
pythonpath = "fastapi/app /app"
addopts = "-ra -v"