[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "abrege"
version = "0.0.1"
authors = []
description = "A small langchain summary builder with extractive summary method to speed up summary process"
requires-python = "==3.11.2"
classifiers = [
    "Programming Language :: Python :: 3"
]
dynamic = ["dependencies", "readme"]

[tool.setuptools]
py-modules = ["abrege"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
readme = {file = ["README.md"]}


[tool.poetry]
name = "abrege"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "=3.11.2"
langchain = "^0.1.16"
pytest = "^8.2.0"
langchain-openai = "^0.1.6"
networkx = {extras = ["default"], version = "^3.3"}
nltk = "^3.8.1"
scikit-learn = "^1.4.2"
fastapi = "^0.111.0"
pypdf = "^4.2.0"
chromadb = "^0.5.0"
pysqlite3-binary = "^0.5.2.post3"
