[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "abrege"
version = "0.0.1"
authors = []
description = "A small langchain summary builder with extractive summary method to speed up summary process"
requires-python = "==3.11.2"
classifiers = [
    "Programming Language :: Python :: 3"
]
dynamic = ["dependencies", "readme"]

[tool.setuptools]
py-modules = ["abrege"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
readme = {file = ["README.md"]}