[project]
name = "abrege"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-openai>=0.1.7",
    "langchain==0.1.16",
    "fastapi>=0.115.11",
    "pypdf>=5.4.0",
    "docx2txt>=0.8",
    "unstructured>=0.17.2",
    "python-docx>=1.1.2",
    "pypandoc-binary>=1.15",
    "tenacity>=8.5.0",
    "pymupdf>=1.25.4",
    "uvicorn>=0.34.0",
    "networkx>=3.4.2",
    "scikit-learn>=1.6.1",
    "transformers==4.40.2",
    "tiktoken>=0.9.0",
    "langchain-chroma>=0.1.4",
    "chromadb>=0.5.23",
    "pillow>=11.1.0",
    "python-multipart>=0.0.20",
    "python-dotenv>=1.0.1",
]

[dependency-groups]
frontend = [
    "streamlit>=1.43.2",
]
