[tool.poetry]
name = "abrege"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "=3.11.2" #">=3.12,<3.13"
langchain = "^0.1.16"
openai = "^1.23.1"
ipykernel = "^6.29.4"
langchain-openai = "^0.1.3"
sentence-transformers = "^2.7.0"
fastapi = "^0.110.2"
networkx = {extras = ["default"], version = "^3.3"}
py-pdf-parser = "^0.12.0"
ipywidgets = "^8.1.2"
pytest = "^8.1.1"
httpx = "^0.27.0"
nltk = "^3.8.1"
unstructured = "^0.13.4"
datasets = "^2.19.0"
langchain-community = "^0.0.34"
langchain-core = "^0.1.46"
tiktoken = "^0.6.0"
chromadb = "^0.5.0"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"