name: Trigger dso sync

on:
  push:
    branches:
    - '**'
  workflow_dispatch:

jobs:
  sync:
    uses: ArnaudTA/actions/.github/workflows/sync.yaml@v1
    secrets:
      GILTAB_PROJECT_NAME: "${{ vars.GILTAB_PROJECT_NAME }}"
      GITLAB_MIRROR_ID: "${{ vars.GITLAB_MIRROR_ID }}"
      GITLAB_TRIGGER_TOKEN: "${{ secrets.GITLAB_TRIGGER_TOKEN }}"
      GITLAB_URL: "${{ secrets.GITLAB_URL }}"
    with:
      BRANCH_NAME: ${{ github.ref_name }}
      SYNC_ALL: false
      WAIT: false
