name: Release Beta

on:
  push:
    branches:
      - staging

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: actions-runner-controller

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set beta prerelease info
        id: vars
        run: |
          echo "prerelease=true" >> $GITHUB_OUTPUT
          echo "target_branch=staging" >> $GITHUB_OUTPUT

      - name: Run Release Please for beta
        uses: googleapis/release-please-action@v4
        with:
          release-type: python
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          target-branch: ${{ steps.vars.outputs.target_branch }}
          prerelease: ${{ steps.vars.outputs.prerelease }}
