# .github/workflows/release-rc.yml
name: Release RC

on:
  push:
    branches:
      - preprod

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: actions-runner-controller

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set rc prerelease info
        id: vars
        run: |
          echo "prerelease=true" >> $GITHUB_OUTPUT
          echo "target_branch=preprod" >> $GITHUB_OUTPUT

      - name: Run Release Please for RC
        uses: googleapis/release-please-action@v4
        with:
          release-type: python
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          target-branch: preprod
          config-file: release-please-config.json
          prerelease: ${{ steps.vars.outputs.prerelease }}
